### ISSUE TITLE
PR出す際、どのブランチにめがけておこなえばよいか確認

### ISSUE THREAD

**Issue by gkzz** [youknowcast/jtfparty#16]
# 現状
Master -> Master

**Comment by youknowcast** [comment]
Issueありがとうございます．
これ，今後も考えると，develop, testing, production(呼び方はなんでもよいのですが・・)の 3 種類くらいはほしいなぁと考えています．
それぞれ，どこぞに CD できるとなおよし，と．

**Comment by gkzz** [comment]
> 今後も考えると，develop, testing, production(呼び方はなんでもよいのですが・・)の 3 種類くらいはほしいなぁ

ブランチはこんなかんじでしょうか？
```
production: 一般公開しているブランチ
testing: productionにマージする前にproductionと同程度の環境で動作確認するブランチ
- develop: issue単位？で切られた開発ブランチ、featureのマージ先
+ develop: 後述するfeatureのマージ先
feature: issue単位？で切られた開発ブランチ
```

参考：https://np-complete.gitbook.io/cho-practical-git/noworu

**Comment by youknowcast** [comment]
はい，ご認識の branch の切り方で問題ないと思います！

**Comment by gkzz** [comment]
> はい，ご認識の branch の切り方で問題ないと思います！

おｋです。
github actionsとherokuか、gigaelixirにdevelop, testing, producitonとデプロイできるように検証してもいいですか？

- [GitHub Actions で Heroku の CI 環境を構築する](https://qiita.com/k-seta/items/5d5a4431c9479e6bc45e)
- [使って学ぶgigalixir、DBを使うアプリをデプロイする](https://qiita.com/pojiro/items/efc72557fb00b56a977a)

**Comment by gkzz** [comment]
ブランチの命名規則はこんなかんじですかね？

```
時間軸------------------------> 

production
|
|_develop ----------------------------> testing ----------------------------> production
   |                                   | 
   |_feature/${issue番号}               |_ testing/${開発者}                                              
      |
      |_feature/${issue番号}/${開発者}                                                                                               
```

**Comment by youknowcast** [comment]
testing はひとつでもよいかなぁとは思います〜

GitHub Actions と heroku/gigalixir 連携いいですね！

**Comment by gkzz** [comment]
@youknowcast さんのmasterブランチからdevelopを切っていただけますか？
それを私のローカルでもcheckoutした後、`feature/17`と子ブランチ`feature/17/tamaki`を作ろうかなと。
#17 と連携のissueを作りました。

現在、私のmasterは[完了: セッションリストの seeds 整備 #15](https://github.com/youknowcast/jtfparty/pull/15)が入ってしまっているので。

それが終わればこのissueはクローズで良さそうです。

**Comment by youknowcast** [comment]
@gkzz 
here you are ;)
https://github.com/youknowcast/jtfparty/tree/develop

**Comment by gkzz** [comment]
thx man

**Comment by gkzz** [comment]
/は1回しか使えないらしいのでアンスコで代用しました。
```
- feature/${issue番号}/${開発者}       
+ feature/${issue番号}_${開発者} 
```
issue17の場合
```
$ git branch -r | grep 17
  origin/feature/17
  origin/feature/17_tamaki
```
